spring:
  datasource:
    platform: postgresql
    url: ${JDBC_DATABASE_URL}
    username: bfzpcqyjqefrbk
    password: 619edf6a34a746c2188d33d2e15c28b88b4f37f981e7e8529624e8acc3cc7d22
    driverClassName: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
           
  thymeleaf:
    cache: false
  mvc:
    favicon:
      enabled: false    