spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/userData
    username: postgres
    password: Milano23
    driverClassName: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
           
  thymeleaf:
    cache: false
  mvc:
    favicon:
      enabled: false    